database:
  type: "sqlite"  # "sqlite" or "mysql"
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""


pickaxes:
  custom_pickaxe:
    name: "Custom Pickaxe"
    lore:
      - "A special pickaxe"
    material: "DIAMOND_PICKAXE"
    custom_model_data: 123
    stored_block: "DIAMOND_ORE"
    drop_item: "DIAMOND"  # This specifies the item to be stored
  another_pickaxe:
    name: "Another Pickaxe"
    lore:
      - "Another special pickaxe"
    material: "IRON_PICKAXE"
    custom_model_data: 456
    stored_block: "COAL_ORE"
    drop_item: "COAL"
