database:
  type: "sqlite"  # "sqlite" or "mysql"
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""


pickaxes:
  custom_pickaxe:
    name: "Infinite Pickaxe"
    lore:
      - "A magical pickaxe that stores mined blocks."
    material: "DIAMOND_PICKAXE"
    stored_block: "DIAMOND_ORE"
    custom_model_data: 123
  another_pickaxe:
    name: "Another Pickaxe"
    lore:
      - "Another magical pickaxe."
    material: "IRON_PICKAXE"
    stored_block: "COAL_ORE"
    custom_model_data: 124
