name: InfinitePick
main: org.unknowntehk.infinitepick.InfinitePickaxe
version: 1.0
author: UnknownTehk
api-version: 1.16
commands:
  givepickaxe:
    description: "Gives a custom infinite pickaxe"
    usage: "/givepickaxe <player> <pickaxe_name>"
    permission: "infinitepick.give"
  infinitepickreload:
    description: "Reloads the plugin configuration"
    usage: "/infinitepickreload"
    permission: "infinitepick.reload"
permissions:
  infinitepick.give:
    description: "Allows the user to give the custom pickaxe"
    default: op
  infinitepick.reload:
    description: "Allows the user to reload the plugin"
    default: op
